# Differential reflection-layout parity fixture.
#
# WHY THIS EXISTS
# ---------------
# flisp's raw lowered `Method`/`CodeInfo` layout is a de-facto public API:
# packages read slot names, `slot_syms` past `nargs`, gensym conventions, and
# CodeInfo flags directly (Tissue.jl reads `argnames[m.nargs:end]` off the outer
# Method; KeywordArgumentExtraction.jl reads `Base.kwarg_decl`). Over the course
# of the JuliaLowering compatibility work these surfaces were brought to parity
# one field at a time, each discovered by a PkgEval failure. This fixture pins
# the JL-lane layout for a matrix of method shapes so that any future drift in
# a reflective surface fails loudly here instead of in PkgEval.
#
# HOW IT WORKS
# ------------
# Each shape is lowered through JuliaLowering explicitly via
# `JuliaLowering.include_string` (so the pins hold regardless of whether the
# process lowerer is JL or flisp), then every introspectable layout surface is
# extracted, gensym-number- and module-name-normalized, and compared against a
# pinned expected value. The pins were generated by
# `~/pkgeval-JL-run/reflection-layout/gen_pins.jl` (kept alongside the one-time
# differential dump `dump.jl` / `diff-summary.txt`).
#
# WHAT IS PINNED, AND WHERE JL DIVERGES FROM flisp
# ------------------------------------------------
# The one-time differential dump (JL vs flisp, 34 shapes) found that every
# *consumer-facing* surface is already at parity:
#   * `Base.kwarg_decl`                       — parity on all shapes
#   * outer-method `slot_syms` / `method_argnames` (the Tissue surface) — parity
#   * `nameof` of top-level functions, user-method `show`, user-method CodeInfo
#     (incl. `has_fcall`)                     — parity
# The *only* residual divergences are confined to the internal `Core.kwcall`
# generated method and to one nested-closure naming case. They are pinned here
# at JL's CURRENT behavior (drift detection, not forced parity). Divergent cells
# are flagged inline below with `DIVERGES(flisp: ...)` and a workspace ref:
#
#   D1 kwcall slot naming: JL names the kwcall slots `kws`, `#kwtmp#`,
#      `#kwcall_self#`, `#unused#`; flisp uses `#s<N>`. This is
#      the `#kwtmp#` naming family (Cluster C, commit 9f1566ea2a;
#      bugs/kwtmp-ctor-leak). Benign: `Base.kwarg_decl` filters both to parity.
#      NOTE: the forwarded original-function self slot (a non-leading `#self#`)
#      is now blanked to `Symbol("")` to match flisp -- see the `to_code_info`
#      slotname pass in eval.jl (bugs/methodinspector-c2new). So the kwcall
#      `#self#` cells below now read `` (blank), matching the flisp reference.
#   D2 kwcall kw-slot ORDER differs (JL keeps declaration order + trailing
#      `#kwtmp#`; flisp interleaves an empty tmp cell). Internal to the kwcall
#      body; `kwarg_decl` is parity. Benign.
#   D3 kwcall `ci.slotflags`: JL emits 0 on the self/tmp slots where flisp marks
#      them used (8) / used+assigned (24). Recomputed by inference. Benign.
#   D4 (FIXED) kwcall `.name` for a nested kw closure now reports the closure's
#      OWN name (`h`), matching flisp, and the closure type name orders its
#      components own-first (`#h#outer4##N`). Previously JL reported the enclosing
#      function name (`outer4`) with the components reversed; that defeated
#      `Method.name`/`nameof`/`StackFrame.func` for any named local closure
#      (bugs/nested-closure-nameof: Pretend.jl keys `first(methods(f)).name`,
#      MIRTjim reads `stacktrace()[level].func`). Pinned here at the corrected
#      value; see `closure_type_basename` in closure_conversion.jl.
#   D5 `f(var"#self#") = 1`: flisp raises `syntax: function argument name not
#      unique: "#self#"`; JL accepts it (a second disambiguated `#self#` slot).
#      JL is *more* permissive, so no compiling package can depend on flisp's
#      error. Benign; pinned to catch future change in either direction.
#
# No class-(c) (consumer-plausible) divergence was found: the two historically
# consumer-visible surfaces (outer `slot_syms` = Tissue; `kwarg_decl` =
# KeywordArgumentExtraction) are now at parity, confirming those fixes converged.
#
# Ledger: ~/pkgeval-JL-run/bugs/reflection-layout-parity/notes.md

using Test
using JuliaLowering

# ---------------------------------------------------------------- normalization
# Strip lane/gen module names; collapse counters inside gensym-ish tokens to N.
function _rp_norm(s::AbstractString)
    s = replace(s, r"mgen_[A-Za-z0-9_]+" => "MOD")
    # Canonicalize the function self-type rendering, which is binding-reachability
    # dependent (`typeof(Main.MOD.f)` vs `Main.MOD.var"#f"`).
    s = replace(s, r"(?:Main\.)?MOD\.var\"#([A-Za-z_][A-Za-z0-9_!]*)\"" => s"typeof(MOD.\1)")
    s = replace(s, "typeof(Main.MOD." => "typeof(MOD.")
    s = replace(s, r"[#\w]*#[#\w]*" => t -> replace(t, r"\d+" => "N"))
    return s
end
_rp_norm(x) = _rp_norm(string(x))
_rp_nsyms(v) = "[" * join((_rp_norm(x) for x in v), ", ") * "]"

# ---------------------------------------------------------------- extraction
_rp_argnames(m) = ccall(:jl_uncompress_argnames, Vector{Symbol}, (Any,), m.slot_syms)
_rp_hasfcall(m) = try Base.uncompressed_ir(m).has_fcall catch; missing end
_rp_slotflags(m) = try string(Int.(Base.uncompressed_ir(m).slotflags)) catch; "generated" end

function _rp_outer_methods(mod, primaries)
    ms = Any[]
    for p in primaries
        isdefined(mod, p) || continue
        v = Base.invokelatest(getglobal, mod, p)
        (v isa Function || v isa Type) || continue
        append!(ms, collect(methods(v)))
    end
    ms
end
_rp_kwcall_methods(mod) = [m for m in methods(Core.kwcall) if m.module === mod]

# Lower `code` through JuliaLowering and return the normalized layout record.
function _rp_record(code, primaries, modname)
    mod = Module(Symbol(modname))
    Core.eval(mod, :(using Base))
    Core.eval(mod, :(import Base: @kwdef, @nospecialize, @nospecializeinfer, @generated))
    JuliaLowering.include_string(mod, code)
    oms = _rp_outer_methods(mod, primaries)
    outer = sort([(sig=_rp_norm(m.sig), slot_syms=_rp_nsyms(_rp_argnames(m)),
                   nargs=Int(m.nargs), isva=m.isva,
                   kwarg_decl=_rp_nsyms(Base.kwarg_decl(m)),
                   has_fcall=_rp_hasfcall(m)) for m in oms], by=x->x.sig)
    kms = _rp_kwcall_methods(mod)
    kwcall = sort([(slot_syms=_rp_nsyms(_rp_argnames(m)), nargs=Int(m.nargs),
                    isva=m.isva, name=_rp_norm(m.name),
                    slotflags=_rp_slotflags(m)) for m in kms], by=x->x.slot_syms)
    nofs = String[]
    for p in primaries
        if isdefined(mod, p)
            v = Base.invokelatest(getglobal, mod, p)
            try; push!(nofs, _rp_norm(nameof(v))); catch; end
        end
    end
    return (outer=outer, kwcall=kwcall, nameof=nofs)
end

# ---------------------------------------------------------------- shape matrix
# name => (code, primaries)
const _RP_SHAPES = Pair{String,Tuple{String,Vector{Symbol}}}[
    "plain_positional" => ("f(x, y) = x + y", [:f]),
    "optional_positional" => ("f(x, y=2, z=3) = x + y + z", [:f]),
    "required_kw" => ("f(x; a) = x + a", [:f]),
    "optional_kw" => ("f(x; a=1) = x + a", [:f]),
    "restkw_only" => ("f(x; kwargs...) = x", [:f]),
    "mixed_kw" => ("f(x, y=2; a=1, b, kw...) = x + y + a + b", [:f]),
    "required_and_rest_kw" => ("f(x; a, kwargs...) = x + a", [:f]),
    "nospecialize_arg" => ("f(@nospecialize(x), y) = y", [:f]),
    "nospecializeinfer_fn" => ("Base.@nospecializeinfer f(@nospecialize(x)) = x", [:f]),
    "varargs" => ("f(x, ys...) = x", [:f]),
    "varargs_typed" => ("f(x, ys::Int...) = x", [:f]),
    "vararg_annot_N" => ("f(x, ys::Vararg{Int,2}) = x", [:f]),
    "where_param" => ("f(x::T) where {T} = T", [:f]),
    "where_two" => ("f(x::T, y::S) where {T,S<:T} = (T,S)", [:f]),
    "where_sparam_closure" => ("function f(x::T) where {T}; () -> T; end", [:f]),
    "closure_named_local" => ("function outer(); g(z) = z + 1; g; end", [:outer]),
    "closure_anon" => ("outer2() = (z -> z + 1)", [:outer2]),
    "closure_do_block" => ("outer3(c) = map(x -> x + 1, c)", [:outer3]),
    "closure_kw" => ("function outer4(); h(z; a=1) = z + a; h; end", [:outer4]),
    "callable_struct" => ("struct C; v; end; (c::C)(x) = c.v + x", [:C]),
    "callable_struct_kw" => ("struct D; v; end; (d::D)(x; a=1) = d.v + x + a", [:D]),
    "generated_fn" => ("@generated g(x) = :(x)", [:g]),
    "inner_ctor" => ("struct S; x::Int; S(x) = new(x); end", [:S]),
    "inner_outer_ctor" => ("struct P{T}; x::T; P{T}(x) where {T} = new{T}(x); end", [:P]),
    "kwdef_struct" => ("Base.@kwdef struct K; x::Int = 1; y::Int = 2; end", [:K]),
    "destructured_arg" => ("f((a, b)) = a + b", [:f]),
    "destructured_arg_nested" => ("f((a, (b, c))) = a + b + c", [:f]),
    "underscore_arg" => ("f(_, x) = x", [:f]),
    "underscore_two" => ("f(_, _) = 1", [:f]),
    "macro_generated_def" => ("@eval f(\$(:x)) = x", [:f]),
    "doc_annotated" => ("\"docstring for f\"\nf(x) = x", [:f]),
    "typed_kw" => ("f(x; a::Int=1) = x + a", [:f]),
    "kw_default_ref_prev" => ("f(; a=1, b=a+1) = a + b", [:f]),
    "self_named_arg" => ("f(var\"#self#\") = 1", [:f]),
]

# ---------------------------------------------------------------- pinned layout
# JL-lane layout (generated by reflection-layout/gen_pins.jl). Cells that diverge
# from flisp are annotated D1..D5 per the header; all kwcall entries carry D1/D3.
const _RP_EXPECTED = Dict{String,Any}(
    "plain_positional" => (outer=[(sig="Tuple{typeof(MOD.f), Any, Any}", slot_syms="[#self#, x, y]", nargs=3, isva=false, kwarg_decl="[]", has_fcall=false), ], kwcall=[], nameof=["f", ]),
    "optional_positional" => (outer=[(sig="Tuple{typeof(MOD.f), Any, Any, Any}", slot_syms="[#self#, x, y, z]", nargs=4, isva=false, kwarg_decl="[]", has_fcall=false), (sig="Tuple{typeof(MOD.f), Any, Any}", slot_syms="[#self#, x, y]", nargs=3, isva=false, kwarg_decl="[]", has_fcall=false), (sig="Tuple{typeof(MOD.f), Any}", slot_syms="[#self#, x, y]", nargs=2, isva=false, kwarg_decl="[]", has_fcall=false), ], kwcall=[], nameof=["f", ]),
    "required_kw" => (outer=[(sig="Tuple{typeof(MOD.f), Any}", slot_syms="[#self#, x, a]", nargs=2, isva=false, kwarg_decl="[a]", has_fcall=false), ], kwcall=[(slot_syms="[#unused#, kws, , x, a, #kwtmp#]", nargs=4, isva=false, name="f", slotflags="[0, 8, 8, 8, 0, 8]"), ], nameof=["f", ]),  # kwcall: D1 D3 (flisp slot_syms=[#unused#, , , x, , a] slotflags=[0,8,8,8,8,24])
    "optional_kw" => (outer=[(sig="Tuple{typeof(MOD.f), Any}", slot_syms="[#self#, x]", nargs=2, isva=false, kwarg_decl="[a]", has_fcall=false), ], kwcall=[(slot_syms="[#unused#, kws, , x, a, #kwtmp#]", nargs=4, isva=false, name="f", slotflags="[0, 8, 8, 8, 0, 8]"), ], nameof=["f", ]),  # kwcall: D1 D3 (flisp slot_syms=[#unused#, , , x, a, ])
    "restkw_only" => (outer=[(sig="Tuple{typeof(MOD.f), Any}", slot_syms="[#self#, x]", nargs=2, isva=false, kwarg_decl="[kwargs...]", has_fcall=false), ], kwcall=[(slot_syms="[#unused#, kws, , x, kwargs...]", nargs=4, isva=false, name="f", slotflags="[0, 8, 8, 8, 0]"), ], nameof=["f", ]),  # kwcall: D1 D3 (flisp slot_syms=[#unused#, , , x, kwargs...])
    "mixed_kw" => (outer=[(sig="Tuple{typeof(MOD.f), Any, Any}", slot_syms="[#self#, x, y, a, b]", nargs=3, isva=false, kwarg_decl="[a, b, kw...]", has_fcall=false), (sig="Tuple{typeof(MOD.f), Any}", slot_syms="[#self#, x]", nargs=2, isva=false, kwarg_decl="[...]", has_fcall=false), ], kwcall=[(slot_syms="[#kwcall_self#, kws, , x, y, a, b, kw..., #kwtmp#]", nargs=5, isva=false, name="f", slotflags="[0, 8, 8, 8, 8, 0, 0, 0, 8]"), (slot_syms="[#kwcall_self#, kws, , x]", nargs=4, isva=false, name="f", slotflags="[72, 8, 8, 8]"), ], nameof=["f", ]),  # kwcall: D1 D2 D3 (flisp slot_syms=[#sN, , , x, y, , a, kw..., b])
    "required_and_rest_kw" => (outer=[(sig="Tuple{typeof(MOD.f), Any}", slot_syms="[#self#, x, a]", nargs=2, isva=false, kwarg_decl="[a, kwargs...]", has_fcall=false), ], kwcall=[(slot_syms="[#unused#, kws, , x, a, kwargs..., #kwtmp#]", nargs=4, isva=false, name="f", slotflags="[0, 8, 8, 8, 0, 0, 8]"), ], nameof=["f", ]),  # kwcall: D1 D2 D3 (flisp slot_syms=[#unused#, , , x, , kwargs..., a])
    "nospecialize_arg" => (outer=[(sig="Tuple{typeof(MOD.f), Any, Any}", slot_syms="[#self#, x, y]", nargs=3, isva=false, kwarg_decl="[]", has_fcall=false), ], kwcall=[], nameof=["f", ]),
    "nospecializeinfer_fn" => (outer=[(sig="Tuple{typeof(MOD.f), Any}", slot_syms="[#self#, x]", nargs=2, isva=false, kwarg_decl="[]", has_fcall=false), ], kwcall=[], nameof=["f", ]),
    "varargs" => (outer=[(sig="Tuple{typeof(MOD.f), Any, Vararg{Any}}", slot_syms="[#self#, x, ys]", nargs=3, isva=true, kwarg_decl="[]", has_fcall=false), ], kwcall=[], nameof=["f", ]),
    "varargs_typed" => (outer=[(sig="Tuple{typeof(MOD.f), Any, Vararg{Int64}}", slot_syms="[#self#, x, ys]", nargs=3, isva=true, kwarg_decl="[]", has_fcall=false), ], kwcall=[], nameof=["f", ]),
    "vararg_annot_N" => (outer=[(sig="Tuple{typeof(MOD.f), Any, Int64, Int64}", slot_syms="[#self#, x, ys]", nargs=3, isva=true, kwarg_decl="[]", has_fcall=false), ], kwcall=[], nameof=["f", ]),
    "where_param" => (outer=[(sig="Tuple{typeof(MOD.f), T} where T", slot_syms="[#self#, x]", nargs=2, isva=false, kwarg_decl="[]", has_fcall=false), ], kwcall=[], nameof=["f", ]),
    "where_two" => (outer=[(sig="Tuple{typeof(MOD.f), T, S} where {T, S<:T}", slot_syms="[#self#, x, y]", nargs=3, isva=false, kwarg_decl="[]", has_fcall=false), ], kwcall=[], nameof=["f", ]),
    "where_sparam_closure" => (outer=[(sig="Tuple{typeof(MOD.f), T} where T", slot_syms="[#self#, x, #->#]", nargs=2, isva=false, kwarg_decl="[]", has_fcall=false), ], kwcall=[], nameof=["f", ]),
    "closure_named_local" => (outer=[(sig="Tuple{typeof(MOD.outer)}", slot_syms="[#self#, g]", nargs=1, isva=false, kwarg_decl="[]", has_fcall=false), ], kwcall=[], nameof=["outer", ]),
    "closure_anon" => (outer=[(sig="Tuple{typeof(MOD.outer2)}", slot_syms="[#self#, #->#]", nargs=1, isva=false, kwarg_decl="[]", has_fcall=false), ], kwcall=[], nameof=["outer2", ]),
    "closure_do_block" => (outer=[(sig="Tuple{typeof(MOD.outer3), Any}", slot_syms="[#self#, c, #->#]", nargs=2, isva=false, kwarg_decl="[]", has_fcall=false), ], kwcall=[], nameof=["outer3", ]),
    "closure_kw" => (outer=[(sig="Tuple{typeof(MOD.outer4)}", slot_syms="[#self#, #kw_body#h#N, h]", nargs=1, isva=false, kwarg_decl="[]", has_fcall=false), ], kwcall=[(slot_syms="[#unused#, kws, , z, a, #kwtmp#]", nargs=4, isva=false, name="h", slotflags="[0, 8, 8, 8, 0, 8]"), ], nameof=["outer4", ]),  # kwcall: D1 D3 (D4 fixed: name=h and closure type #h#outer4# now match flisp)
    "callable_struct" => (outer=[(sig="Tuple{Type{Main.MOD.C}, Any}", slot_syms="[#ctor-self#, v]", nargs=2, isva=false, kwarg_decl="[]", has_fcall=false), ], kwcall=[], nameof=["C", ]),
    "callable_struct_kw" => (outer=[(sig="Tuple{Type{Main.MOD.D}, Any}", slot_syms="[#ctor-self#, v]", nargs=2, isva=false, kwarg_decl="[]", has_fcall=false), ], kwcall=[(slot_syms="[#unused#, kws, d, x, a, #kwtmp#]", nargs=4, isva=false, name="D", slotflags="[0, 8, 8, 8, 0, 8]"), ], nameof=["D", ]),  # kwcall: D1 D3 (flisp slot_syms=[#unused#, , d, x, a, ])
    "generated_fn" => (outer=[(sig="Tuple{typeof(MOD.g), Any}", slot_syms="[#self#, x]", nargs=2, isva=false, kwarg_decl="[]", has_fcall=missing), ], kwcall=[], nameof=["g", ]),
    "inner_ctor" => (outer=[(sig="Tuple{Type{Main.MOD.S}, Any}", slot_syms="[#ctor-self#, x, tmp]", nargs=2, isva=false, kwarg_decl="[]", has_fcall=false), ], kwcall=[], nameof=["S", ]),
    "inner_outer_ctor" => (outer=[], kwcall=[], nameof=["P", ]),
    "kwdef_struct" => (outer=[(sig="Tuple{Type{Main.MOD.K}, Any, Any}", slot_syms="[#ctor-self#, x, y, , ]", nargs=3, isva=false, kwarg_decl="[]", has_fcall=false), (sig="Tuple{Type{Main.MOD.K}, Int64, Int64}", slot_syms="[#ctor-self#, x, y]", nargs=3, isva=false, kwarg_decl="[]", has_fcall=false), (sig="Tuple{Type{Main.MOD.K}}", slot_syms="[#self#]", nargs=1, isva=false, kwarg_decl="[x, y]", has_fcall=false), ], kwcall=[(slot_syms="[#unused#, kws, , x, y, #kwtmp#]", nargs=3, isva=false, name="K", slotflags="[0, 8, 8, 0, 0, 8]"), ], nameof=["K", ]),  # kwcall: D1 D3
    "destructured_arg" => (outer=[(sig="Tuple{typeof(MOD.f), Any}", slot_syms="[#self#, destructured, iterstate, a, b]", nargs=2, isva=false, kwarg_decl="[]", has_fcall=false), ], kwcall=[], nameof=["f", ]),
    "destructured_arg_nested" => (outer=[(sig="Tuple{typeof(MOD.f), Any}", slot_syms="[#self#, destructured, iterstate, iterstate@1, a, b, c]", nargs=2, isva=false, kwarg_decl="[]", has_fcall=false), ], kwcall=[], nameof=["f", ]),
    "underscore_arg" => (outer=[(sig="Tuple{typeof(MOD.f), Any, Any}", slot_syms="[#self#, #unused#, x]", nargs=3, isva=false, kwarg_decl="[]", has_fcall=false), ], kwcall=[], nameof=["f", ]),
    "underscore_two" => (outer=[(sig="Tuple{typeof(MOD.f), Any, Any}", slot_syms="[#self#, #unused#, #unused#]", nargs=3, isva=false, kwarg_decl="[]", has_fcall=false), ], kwcall=[], nameof=["f", ]),
    "macro_generated_def" => (outer=[(sig="Tuple{typeof(MOD.f), Any}", slot_syms="[#self#, x]", nargs=2, isva=false, kwarg_decl="[]", has_fcall=false), ], kwcall=[], nameof=["f", ]),
    "doc_annotated" => (outer=[(sig="Tuple{typeof(MOD.f), Any}", slot_syms="[#self#, x]", nargs=2, isva=false, kwarg_decl="[]", has_fcall=false), ], kwcall=[], nameof=["f", ]),
    "typed_kw" => (outer=[(sig="Tuple{typeof(MOD.f), Any}", slot_syms="[#self#, x]", nargs=2, isva=false, kwarg_decl="[a]", has_fcall=false), ], kwcall=[(slot_syms="[#unused#, kws, , x, a, #kwtmp#]", nargs=4, isva=false, name="f", slotflags="[0, 8, 8, 8, 0, 8]"), ], nameof=["f", ]),  # kwcall: D1 D3
    "kw_default_ref_prev" => (outer=[(sig="Tuple{typeof(MOD.f)}", slot_syms="[#self#, a, b]", nargs=1, isva=false, kwarg_decl="[a, b]", has_fcall=false), ], kwcall=[(slot_syms="[#unused#, kws, , #kwtmp#, a, b]", nargs=3, isva=false, name="f", slotflags="[0, 8, 8, 8, 24, 24]"), ], nameof=["f", ]),  # kwcall: D1 D2 D3 (flisp slot_syms=[#unused#, , , , a, b])
    "self_named_arg" => (outer=[(sig="Tuple{typeof(MOD.f), Any}", slot_syms="[#self#, ]", nargs=2, isva=false, kwarg_decl="[]", has_fcall=false), ], kwcall=[], nameof=["f", ]),  # D5: flisp raises "argument name not unique: #self#"; JL accepts, and (like flisp's CodeInfo pass) blanks the non-leading `#self#` slot.
)

# ---------------------------------------------------------------- the fixture
@testset "reflection layout parity" begin
    @testset "$name" for (name, (code, primaries)) in _RP_SHAPES
        exp = _RP_EXPECTED[name]
        got = _rp_record(code, primaries, "mgen_$name")
        # Compare outer methods (Tissue / kwarg_decl / nameof consumer surfaces).
        @test isequal([NamedTuple(r) for r in got.outer], [NamedTuple(r) for r in exp.outer])
        # Compare internal kwcall method layout (pinned incl. known divergences).
        @test isequal([NamedTuple(r) for r in got.kwcall], [NamedTuple(r) for r in exp.kwcall])
        @test got.nameof == collect(exp.nameof)
    end
end
