include(joinpath(@__DIR__, "straight_gen_inc.jl"))
Core.eval(Main, straight_expr(65536))
Base.invokelatest(bench_f, 1.5)
m = only(methods(bench_f))
mi = only(Base.specializations(m))
ptr = reinterpret(Ptr{UInt8}, getfield(mi.cache, :specptr))
glue = Vector{UInt8}(undef, 65536)
unsafe_copyto!(pointer(glue), ptr, 65536)
write(joinpath(@__DIR__, "parent.bin"), glue)
println(stderr, "parent dumped from ", ptr)
